version: "3.7"

networks:
  application:
  data:

services:
  api:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: [python3, run.py, --host, 0.0.0.0]
    networks:
      - application
      - data
    volumes:
      - ./app:/app
    stdin_open: true
    tty: true
